apiVersion: backstage.io/v1alpha1
kind: component
metadata:
  name: design-system
  description: This is the repository for the website used to document the SSB component library.
  links:
    - title: SSB Design System
      url: https://design.ssb.no
  tags:
    - typescript
    - javascript
    - react
    - scss
    - github-pages
  annotations:
    github.com/project-slug: statisticsnorway/design-system
spec:
  type: website
  system: SSBNO
  owner: ssbno-developers
  lifecycle: production
  dependsOn:
    - component:component-library
